### ISSUE TITLE
support roof is suspended!

### ISSUE THREAD

**Issue by zhangjiangzhao123** [ThomasRahm/CuraEngine#11]
Dear ThomasRahm, I may have discovered a glitch. When I set ”`support_roof_pattern`“=`Lines`, and `Support Roof Line Directions`=`[0,90]`, it will produce the effect of the picture below. Obviously part of the roof is suspended. This model will not print successfully.
![image](https://user-images.githubusercontent.com/67377386/227484906-ed9f3af9-9330-47e1-aff0-37a6ee767917.png)

![image](https://user-images.githubusercontent.com/67377386/227487177-f1a45baf-d117-4bd0-a34f-c0a8733b07e2.png)

**”`support_roof_pattern`“=`Zigzag` is also have this problem**

![image](https://user-images.githubusercontent.com/67377386/227490329-0e23f8cd-b1fd-4a0c-9e65-c46131671556.png)

**`Support Roof Line Directions`=`[90，180] either.**
![image](https://user-images.githubusercontent.com/67377386/227492156-03c7c0ac-6dbe-4675-b029-2ba78f411328.png)

My test model and gcode files are in the following zip file.
[test_model.zip](https://github.com/ThomasRahm/CuraEngine/files/11060829/test_model.zip)

**Comment by ThomasRahm** [comment]
The first two pictures seem fine to me. Only the bottom-most interface layer is supported as this layer will support the interface above.
The last two do not. This line should be supported

**Comment by ThomasRahm** [comment]
The issue with the last two is fixed (in the code). Thank you for reporting it.
Seems to be that the behavior of regular for lines is a bit different to other infill patterns, so the first two may also be considered a bug. Not sure if this one is fixable, as the code assumes that each roof area the roof area above it supports. As a workaround i recommend setting `Support Roof Wall Line Count` (new setting in 5.3) to 1.

**Comment by zhangjiangzhao123** [comment]
Thanks, The last two situations have been resolved well. For the first two, adding an outer contour(wall) is indeed a better option. I will try to follow your advice.

**Comment by zhangjiangzhao123** [comment]
By the way, I know if `Infill` class:  `fill_gaps = false `, no dangling segments like last two will be generated. It seems that these line segments are extra generated. So where might it come from?

**Comment by ThomasRahm** [comment]
I don't know. To determine how to support the support roof I just call the Infill class with the same parameters that are later used in FFFGcodeWriter when calculating the support roof. My code does not handle the placement of the roof lines.
The only reasons I did not see the change of the Infill class that caused the issue earlier are that the Infill class has a lot of optional parameters and using Polygons* for a bool does not cause an error.

**Comment by zhangjiangzhao123** [comment]
Thank you. This may be an upstream bug.
