### ISSUE TITLE
Outdated fdmprinter.def.json

### ISSUE THREAD

**Issue by pedroloco2** [ThomasRahm/CuraEngine#12]
Hi Thomas, I would appreciate it if you could update the fdmprinter.def.json file, as it is out of date with respect to the latest  "[tree_support_2](https://github.com/ThomasRahm/CuraEngine/tree/tree_support_2)" branch updates.

PD. I take this opportunity to thank you for your improvements regarding tree supports, which are "spearheads" for slicers to resume their focus on the supports area, one of the most important in 3d printing in general.

**Application Version**
UltiMaker Cura 5.3.0-alpha+xmas

**Comment by ThomasRahm** [comment]
I only update the `fdmprinter.def.json` when i release a new Version.
Currently i do not plan on releasing a new Version, as it seems like the tree support will be part of the next Cura version.

An as of now current `fdmprinter.def.json` can be found here:
https://github.com/Ultimaker/Cura/pull/15074

If for some reason (e.g. me changing too much in too little time, i changed like 500 LoC last week) it is not part of Cura 5.4 I may release another Version here and will then update the `fdmprinter.def.json`.
