### ISSUE TITLE
Merge?

### ISSUE THREAD

**Issue by Hello1024** [ThomasRahm/CuraEngine#3]
Did you attempt to get this merged into Cura?   Is there a PR?

**Comment by ThomasRahm** [comment]
There is a [draft PR](https://github.com/Ultimaker/CuraEngine/pull/1282). I hope to get a bit more feedback (and i also need to update when I have time) before removing draft status.  When/if I ask them to look at the over 4000 lines of code I want it to be as good as possible.

**Comment by chrisvanderpennen** [comment]
I'm still using this as my daily and tbh I think it's a shame it's getting slept on by not just Cura but the likes of prusaslicer/superslicer/etc.  It's _so much better_ than the stock Cura tree supports - which I'm pretty sure Bambu imported into their prusaslicer fork.

**Comment by DerGenaue** [comment]
I actually checked the source,
Bambu did indeed port the original Cura Tree Support.
There is definitely some attention around this Implementation (@ThomasRahm plz consider getting your PR out of the draft state);
I'm pretty sure Prusa is aware, too.

**Comment by DerGenaue** [comment]
> tbh I think it's a shame it's getting slept on by not just Cura but the likes of prusaslicer/superslicer/etc.

@chrisvanderpennen 
There you go; now it is public that the new "organic support" that'll be released with the next Prusa Slicer version (2.6) is based on this Tree Support Fork!
Cura also seems to have accelerated their efforts to merge this Fork, so exciting times ahead!
